# Generated by Django 5.1.3 on 2024-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(null=True)),
                ('estimated_owners', models.CharField(max_length=50)),
                ('peak_ccu', models.IntegerField()),
                ('required_age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dlc_count', models.IntegerField()),
                ('about_the_game', models.TextField()),
                ('supported_languages', models.TextField(null=True)),
                ('full_audio_languages', models.TextField(null=True)),
                ('reviews', models.TextField(null=True)),
                ('header_image', models.URLField(max_length=500, null=True)),
                ('website', models.URLField(max_length=500, null=True)),
                ('support_url', models.URLField(max_length=500, null=True)),
                ('support_email', models.EmailField(max_length=254, null=True)),
                ('windows', models.BooleanField()),
                ('mac', models.BooleanField()),
                ('linux', models.BooleanField()),
                ('metacritic_score', models.IntegerField(null=True)),
                ('metacritic_url', models.URLField(max_length=500, null=True)),
                ('user_score', models.IntegerField(null=True)),
                ('positive', models.IntegerField(null=True)),
                ('negative', models.IntegerField(null=True)),
                ('achievements', models.IntegerField(null=True)),
                ('recommendations', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('average_playtime_forever', models.IntegerField(null=True)),
                ('average_playtime_two_weeks', models.IntegerField(null=True)),
                ('median_playtime_forever', models.IntegerField(null=True)),
                ('median_playtime_two_weeks', models.IntegerField(null=True)),
                ('developers', models.TextField(null=True)),
                ('publishers', models.TextField(null=True)),
                ('categories', models.TextField(null=True)),
                ('genres', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('screenshots', models.TextField(null=True)),
                ('movies', models.TextField(null=True)),
            ],
        ),
    ]
