# Generated by Django 5.1.4 on 2024-12-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullAudioLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_audio_language', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_language', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('release_date', models.DateField()),
                ('estimated_owners', models.IntegerField(null=True)),
                ('peak_concurrent_users', models.IntegerField(null=True)),
                ('required_age', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dlc_count', models.IntegerField(default=0)),
                ('about_the_game', models.TextField(null=True)),
                ('header_image', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
                ('support_url', models.URLField(null=True)),
                ('support_email', models.EmailField(max_length=254, null=True)),
                ('windows', models.BooleanField(default=False)),
                ('mac', models.BooleanField(default=False)),
                ('linux', models.BooleanField(default=False)),
                ('metacritic_score', models.IntegerField(null=True)),
                ('metacritic_url', models.URLField(null=True)),
                ('positive_ratings', models.IntegerField(null=True)),
                ('negative_ratings', models.IntegerField(null=True)),
                ('achievements', models.IntegerField(null=True)),
                ('average_playtime', models.IntegerField(default=0)),
                ('median_playtime', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='api.category')),
                ('developers', models.ManyToManyField(blank=True, to='api.developer')),
                ('full_audio_languages', models.ManyToManyField(blank=True, to='api.fullaudiolanguage')),
                ('genres', models.ManyToManyField(blank=True, to='api.genre')),
                ('publishers', models.ManyToManyField(blank=True, to='api.publisher')),
                ('supported_languages', models.ManyToManyField(blank=True, to='api.supportedlanguage')),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
            ],
        ),
    ]
