# Generated by Django 5.1.3 on 2024-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='peak_ccu',
            field=models.IntegerField(null=True),
        ),
    ]
