# Generated by Django 5.1.3 on 2024-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_peak_ccu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='about_the_game',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dlc_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='estimated_owners',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='linux',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mac',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='required_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='windows',
            field=models.BooleanField(null=True),
        ),
    ]
