# Generated by Django 5.1.4 on 2024-12-19 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_achievements_alter_game_average_playtime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='game',
            name='required_age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
