from django.db import models


class Game(models.Model):
    name = models.CharField(max_length=255, null=False)
    release_date = models.DateField(null=True)
    estimated_owners = models.CharField(max_length=50, null=True)
    peak_ccu = models.IntegerField(null=True)
    required_age = models.IntegerField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    dlc_count = models.IntegerField(null=True)
    about_the_game = models.TextField(null=True)
    supported_languages = models.TextField(null=True)
    full_audio_languages = models.TextField(null=True)
    reviews = models.TextField(null=True)
    header_image = models.URLField(max_length=500, null=True)
    website = models.URLField(max_length=500, null=True)
    support_url = models.URLField(max_length=500, null=True)
    support_email = models.EmailField(null=True)
    windows = models.BooleanField(null=True)
    mac = models.BooleanField(null=True)
    linux = models.BooleanField(null=True)
    metacritic_score = models.IntegerField(null=True)
    metacritic_url = models.URLField(max_length=500, null=True)
    user_score = models.IntegerField(null=True)
    positive = models.IntegerField(null=True)
    negative = models.IntegerField(null=True)
    achievements = models.IntegerField(null=True)
    recommendations = models.IntegerField(null=True)
    notes = models.TextField(null=True)
    average_playtime_forever = models.IntegerField(null=True)
    average_playtime_two_weeks = models.IntegerField(null=True)
    median_playtime_forever = models.IntegerField(null=True)
    median_playtime_two_weeks = models.IntegerField(null=True)
    developers = models.TextField(null=True)
    publishers = models.TextField(null=True)
    categories = models.TextField(null=True)
    genres = models.TextField(null=True)
    tags = models.TextField(null=True)
    screenshots = models.TextField(null=True)
    movies = models.TextField(null=True)
